### ISSUE TITLE
Having a issues in deploying in netlify

### ISSUE THREAD

**Issue by DracoGamer38** [AnshumanMahato/Happy-Birthday-Card#22]
2:26:13 PM: build-image version: 3ffff9df3d5419545acc1b673a54de348174406d (focal)
2:26:13 PM: buildbot version: 234adcfe967f1d318bfad465ff22f561d657197d
2:26:13 PM: Fetching cached dependencies
2:26:13 PM: Failed to fetch cache, continuing with build
2:26:13 PM: Starting to prepare the repo for build
2:26:13 PM: No cached dependencies found. Cloning fresh repo
2:26:13 PM: git clone --filter=blob:none https://github.com/AnshumanMahato/Happy-Birthday-Card
2:26:14 PM: Preparing Git Reference refs/heads/main
2:26:16 PM: Starting to install dependencies
2:26:16 PM: Python version set to 3.8
2:26:16 PM: Attempting Ruby version 2.7.2, read from environment
2:26:17 PM: Using Ruby version 2.7.2
2:26:17 PM: Started restoring cached go cache
2:26:17 PM: Finished restoring cached go cache
2:26:18 PM: go version go1.19.13 linux/amd64
2:26:18 PM: Using PHP version 8.0
2:26:20 PM: Downloading and installing node v18.19.0...
2:26:20 PM: Downloading https://nodejs.org/dist/v18.19.0/node-v18.19.0-linux-x64.tar.xz...
2:26:20 PM: Computing checksum with sha256sum
2:26:20 PM: Checksums matched!
2:26:22 PM: Now using node v18.19.0 (npm v10.2.3)
2:26:22 PM: Enabling Node.js Corepack
2:26:23 PM: Started restoring cached build plugins
2:26:23 PM: Finished restoring cached build plugins
2:26:23 PM: Started restoring cached corepack dependencies
2:26:23 PM: Finished restoring cached corepack dependencies
2:26:23 PM: No npm workspaces detected
2:26:23 PM: Started restoring cached node modules
2:26:23 PM: Finished restoring cached node modules
2:26:23 PM: Installing npm packages using npm version 10.2.3
2:26:25 PM: npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
2:26:30 PM: added 339 packages, and audited 340 packages in 7s
2:26:30 PM: 121 packages are looking for funding
2:26:30 PM:   run `npm fund` for details
2:26:30 PM: 5 vulnerabilities (3 moderate, 2 high)
2:26:30 PM: To address issues that do not require attention, run:
2:26:30 PM:   npm audit fix
2:26:30 PM: To address all issues (including breaking changes), run:
2:26:30 PM:   npm audit fix --force
2:26:30 PM: Run `npm audit` for details.
2:26:30 PM: npm packages installed
2:26:31 PM: Successfully installed dependencies
2:26:31 PM: Starting build script
2:26:31 PM: Detected 1 framework(s)
2:26:32 PM: "parcel" at version "2.6.2"
2:26:32 PM: Section completed: initializing
2:26:33 PM: ​
2:26:33 PM: Netlify Build                                                 
2:26:33 PM: ────────────────────────────────────────────────────────────────
2:26:33 PM: ​
2:26:33 PM: ❯ Version
2:26:33 PM:   @netlify/build 29.29.4
2:26:33 PM: ​
2:26:33 PM: ❯ Flags
2:26:33 PM:   baseRelDir: true
2:26:33 PM:   buildId: 656af81b4cdb7d247beec3f2
2:26:33 PM:   deployId: 656af81b4cdb7d247beec3f4
2:26:33 PM: ​
2:26:33 PM: ❯ Current directory
2:26:33 PM:   /opt/build/repo
2:26:33 PM: ​
2:26:33 PM: ❯ Config file
2:26:33 PM:   /opt/build/repo/netlify.toml
2:26:33 PM: ​
2:26:33 PM: ❯ Context
2:26:33 PM:   production
2:26:33 PM: ​
2:26:33 PM: build.command from netlify.toml                               
2:26:33 PM: ────────────────────────────────────────────────────────────────
2:26:33 PM: ​
2:26:33 PM: $ npm run build
2:26:34 PM: > happy-birthday-card@3.0.2 build
2:26:34 PM: > npm-run-all init-index-remote build:parcel
2:26:34 PM: > happy-birthday-card@3.0.2 init-index-remote
2:26:34 PM: > node builder/init.js --remote
2:26:34 PM: /opt/build/repo/builder/init.js:14
2:26:34 PM: if (!process.env.PIC) throw new Error("Please specify PIC in environment.");
2:26:34 PM:                       ^
2:26:34 PM: Error: Please specify PIC in environment.
2:26:34 PM:     at Object.<anonymous> (/opt/build/repo/builder/init.js:14:29)
2:26:34 PM:     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2:26:34 PM:     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2:26:34 PM:     at Module.load (node:internal/modules/cjs/loader:1197:32)
2:26:34 PM:     at Module._load (node:internal/modules/cjs/loader:1013:12)
2:26:34 PM:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
2:26:34 PM:     at node:internal/main/run_main_module:28:49
2:26:34 PM: Node.js v18.19.0
2:26:34 PM: ERROR: "init-index-remote" exited with 1.
2:26:34 PM: ​
2:26:34 PM: "build.command" failed                                        
2:26:34 PM: ────────────────────────────────────────────────────────────────
2:26:34 PM: ​
2:26:34 PM:   Error message
2:26:34 PM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
2:26:34 PM: ​
2:26:34 PM:   Error location
2:26:34 PM:   In build.command from netlify.toml:
2:26:34 PM:   npm run build
2:26:34 PM: ​
2:26:34 PM:   Resolved config
2:26:34 PM:   build:
2:26:34 PM:     base: /opt/build/repo
2:26:34 PM:     command: npm run build
2:26:34 PM:     commandOrigin: config
2:26:34 PM:     environment:
2:26:34 PM:       - NAME
2:26:34 PM:     publish: /opt/build/repo/dist
2:26:34 PM:     publishOrigin: config
2:26:35 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
2:26:35 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:26:35 PM: Failing build: Failed to build site
2:26:35 PM: Finished processing build request in 22.186s
![Screenshot_20231202-143948](https://github.com/AnshumanMahato/Happy-Birthday-Card/assets/94850447/f38ba68a-42f8-4536-8929-cb3d555b12aa)

**Comment by AnshumanMahato** [comment]
> if (!process.env.PIC) throw new Error("Please specify PIC in environment.");
> 2:26:34 PM: ^
The logs say you did not specify the PIC var in the environment. Please check that in your deployment.
